distributable:
  url: https://github.com/pyinvoke/invoke/archive/refs/tags/{{version}}.tar.gz
  strip-components: 1

display-name: pyinvoke.org

# if there’s a github then we can parse the versions
versions:
  github: pyinvoke/invoke/tags

dependencies:
  python.org: ^3.13.3

build:
  dependencies:
    cmake.org: ^3
    # ^^ use fully qualified names
  script:
    - python-venv.sh {{prefix}}/bin/invoke


provides:
  - bin/invoke

test:
  dependencies:
    python.org: ^3.13.3
  script:
    - invoke --version | grep "^Invoke {{version}}"

